# Site settings
title: Duane McPherson
email: duanemcpherson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Professional 3D modelling and animation services.
baseurl:  # the subpath of your site, e.g. /blog/
url: www.duanemcpherson.com # the base hostname & protocol for your site
twitter_username: duanemcpherson
github_username:  asphyxiate

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/



# Gems
gems: [jekyll-paginate]

